services:
  tomcat:
    build: .
    container_name: ecommerce_tomcat
    ports:
      - "8081:8080"
  redis:
    image: redis:alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"